In [13]:
import numpy as np

In [14]:
test_list = [[1,4,5,8],[1,4,5,8]]

In [15]:
test_list

[[1, 4, 5, 8], [1, 4, 5, 8]]

In [16]:
print(test_list)

[[1, 4, 5, 8], [1, 4, 5, 8]]


In [17]:
np.array(test_list, float)

array([[1., 4., 5., 8.],
       [1., 4., 5., 8.]])

In [18]:
import numpy as np
test_array = np.array([1,4,5,8], float)
test_array

array([1., 4., 5., 8.])

In [19]:
type(test_array[3])

numpy.float64

In [20]:
test_array = np.array([1,4,5,"8"], float)
print(test_array)

[1. 4. 5. 8.]


In [22]:
print(type(test_array[3]))

<class 'numpy.float64'>


In [23]:
print(test_array.dtype)

float64


In [24]:
print(test_array.shape)

(4,)


In [25]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix,int).shape

(3, 4)

In [26]:
tensor_rank3 = [
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
    ]
np.array(tensor_rank3, int).shape

(4, 3, 4)

In [27]:
np.array(tensor_rank3, int).ndim

3

In [28]:
np.array(tensor_rank3, int).size

48

In [29]:
np.array([[1,2,3.5],[4,5,6.5]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.array([[1,2,3.5],[4,5,6.5]], dtype=float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [31]:
import sys
np.array([[1,2,3.5],[4,5,6.5]], dtype=np.float64).itemsize

8

In [32]:
np.array([[1,2,3.5],[4,5,6.5]], dtype=np.float32).itemsize

4

In [33]:
test_array

array([1., 4., 5., 8.])

In [34]:
test_array.itemsize

8

In [36]:
x = np.array([[1,2,5,8],[1,2,5,8]])
x.shape

(2, 4)

In [37]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [40]:
x = np.array([[1,2,5,8],[1,2,5,8]])
x.shape

(2, 4)

In [43]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [45]:
x =np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [58]:
x.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [47]:
x = np.array([[1,2,5,8],[1,2,5,8]])
x.shape

(2, 4)

In [48]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [49]:
x.reshape(-1,).shape

(8,)

In [52]:
x =np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [53]:
x =np.array(range(1,8))
x

array([1, 2, 3, 4, 5, 6, 7])

In [55]:
x =np.array(range(0,11,2))
x

array([ 0,  2,  4,  6,  8, 10])

In [59]:
x =np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [60]:
x.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [61]:
x=np.array(range(8)).reshape(4,2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [62]:
x.reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [63]:
x.reshape(2,2,-1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [65]:
y = x.reshape(2,-1)

In [72]:
y = x.reshape(2,-1)

In [67]:
x = np.array(range(8)).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [68]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [69]:
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [70]:
x.flatten().size

8

In [71]:
x.flatten().shape

(8,)

In [73]:
x = np.array([[1,2,3],[4,5,6]], int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
x[0][0]

1

In [75]:
x[0,2]

3

In [76]:
x[0,1] = 100
x

array([[  1, 100,   3],
       [  4,   5,   6]])

In [77]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
x[:, 2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [78]:
x[1,1:3]

array([7, 8])

In [79]:
x[1:3]

array([[ 6,  7,  8,  9, 10]])

In [81]:
x = np.array(range(15), int).reshape(3,-1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [82]:
x[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [83]:
x[::2,::3]

array([[ 0,  3],
       [10, 13]])

In [84]:
y = np.array(range(100,2), int)

In [85]:
y

array([], dtype=int32)

In [86]:
y = np.array(range(100,2), int).reshape(2,-1,2)

In [87]:
y

array([], shape=(2, 0, 2), dtype=int32)

In [89]:
y = np.array(range(100), int).reshape(2,-1,2)
y

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39],
        [40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]],

       [[50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59],
        [60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79],
        [80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])